Add handwriting
allenmmo/Cognitive-Vision-Android pull request #1
Opened 2017-03-06 15:07 UTC by allenmmo

Add handwriting OCR client Libray
Add Handwriting OCR in Android Sample app

2017-03-09 06:53 UTC, qiwjin approved these changes

2017-03-09 06:53 UTC, qiwjin commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/contract/HandwritingOCRLine.java
> +    public int[] boundingBox; //bouding box for whole text line, e.g. "boundingBox": [153,579,1310,550,1313,647,156,678].
use points array?

2017-03-09 06:53 UTC, qiwjin commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +        while (operationResult.status.equals("NotStarted") || operationResult.status.equals("Running"));
add retry time?

2017-03-09 06:55 UTC, CommonQ commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceClient.java
> +    public HandwritingOCROperation CreateHandwritingOCROperationAsync(String url) throws  VisionServiceException;
Please use camel case naming convetion.

2017-03-09 07:06 UTC, CommonQ commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/contract/HandwritingOCROperation.java
> +        _url=url;
local variable or local property does not contain underscore prefix.

2017-03-09 07:07 UTC, CommonQ commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/contract/HandwritingOCRWord.java
> +    public int[] boundingBox; //bouding box of the world in origin image, e.g. "boundingBox": [153,579,1310,550,1313,647,156,678].
use ArrayList<int> ?

2017-03-09 07:08 UTC, CommonQ commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/contract/HandwritingOCRLine.java
> +    public List<HandwritingOCRWord> words; //words in the line
private local variables and public getter&setter?

2017-03-09 07:09 UTC, CommonQ commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +        if (id == R.id.action_settings) {
no actual action ?

2017-03-09 07:13 UTC, hippogr requested changes

2017-03-09 07:13 UTC, hippogr commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceRestClient.java
> +        HandwritingOCROperation HandwrittenOCR = new HandwritingOCROperation(operationUrl);
HandwrittenOCR -> handwrittenOCR

2017-03-09 07:13 UTC, hippogr commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceRestClient.java
> +        HandwritingOCROperation HandwrittenOCR = new HandwritingOCROperation(operationUrl);
and other places

2017-03-09 07:13 UTC, hippogr commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +    private EditText mEditText;
unify the naming conventions.

2017-03-09 07:43 UTC, CommonQ commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +        ByteArrayOutputStream output = new ByteArrayOutputStream();
Although it has no effect without closing the ByteArrayOutputStream&ByteArrayInputStream , it's always a good practice to close them.

2017-03-09 07:48 UTC, CommonQ commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +    private class doRequest extends AsyncTask<String, String, String> {
This usage may cause memory leak. 
Inner class inside an activity can maintain a reference to this class. If it continues to perform background work after the Activity has been destroyed, the reference to the Activity will persist and it won’t be garbage collected until after the background task completes.

2017-03-09 07:52 UTC, CommonQ commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +                mEditText.setText("Error: " + e.getMessage());
weak reference is better.

2017-03-09 07:55 UTC, CommonQ requested changes
some advice on this pr

2017-03-09 08:35 UTC, yluiu commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +                            result += word.text + " ";
StringBuilder for concatenation?

2017-03-09 08:51 UTC, yluiu commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +
can add blocking to the select image button in onPreExecute() to avoid click again before result returned

2017-03-09 08:52 UTC, yluiu approved these changes

2017-03-09 13:38 UTC, allenmmo commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +                            result += word.text + " ";
sure

2017-03-09 13:44 UTC, allenmmo commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +
Actually it was blocked before do recognize

2017-03-09 13:59 UTC, allenmmo commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +        while (operationResult.status.equals("NotStarted") || operationResult.status.equals("Running"));
ok

2017-03-09 14:05 UTC, allenmmo commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +        ByteArrayOutputStream output = new ByteArrayOutputStream();
sure

2017-03-09 14:06 UTC, allenmmo commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +        if (id == R.id.action_settings) {
yes, it's seems all of other sample doing the same way

2017-03-09 14:06 UTC, allenmmo commented on Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/HandwritingRecognizeActivity.java
> +    private EditText mEditText;
sure

2017-03-09 14:17 UTC, allenmmo commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceClient.java
> +    public HandwritingOCROperation CreateHandwritingOCROperationAsync(String url) throws  VisionServiceException;
sure

2017-03-09 14:17 UTC, allenmmo commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceRestClient.java
> +        HandwritingOCROperation HandwrittenOCR = new HandwritingOCROperation(operationUrl);
ok

2017-03-10 02:05 UTC, mike-int commented on ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceRestClient.java
> +import com.microsoft.projectoxford.vision.contract.HandwritingReconitionOperationResult;
Change HandwritingReconitionOperationResult 
to          HandwritingRecognitionOperationResult

2017-03-13 11:45 UTC, CommonQ approved these changes

2017-03-13 11:48 UTC, hippogr approved these changes

2017-03-14 02:57 UTC, merged